### ISSUE TITLE
Issues I found during Data Sanity

### ISSUE THREAD

**Issue by Reddragoneer1** [UCSolarCarTeam/Epsilon-Telemetry-Test-Tool#34]
If an issue has a * that means I'm not sure if it's actually an issue or not, but it looked like it was. So if someone could looks at those and confirm or deny that they are issues, that would be great.

Aux is still in music
[`src/BusinessLayer/InternetReporting.cpp`](https://github.com/UCSolarCarTeam/Epsilon-Telemetry-Test-Tool/blob/master/src/BusinessLayer/InternetReporting.cpp)
Line 126

Aux in music
[`src/Tests/BusinessLayer/SerialReportingTest.cpp`](https://github.com/UCSolarCarTeam/Epsilon-Telemetry-Test-Tool/blob/master/src/Tests/BusinessLayer/SerialReportingTest.cpp)
Line 146
Line 337
Util::writeBoolsIntoArray also need to be changed, corresponding to changes made with music

Aux is in music, and Left and Right are switched
[`src/DataLayer/DriverControlsData.h`](https://github.com/UCSolarCarTeam/Epsilon-Telemetry-Test-Tool/blob/master/src/DataLayer/DriverControlsData.h)
Line 14: Aux is still in music
Line 10 and 11: Left and Right are switched
~~Looks as though driver inputs are missing~~ * Not an actual issue

Right and Left Switched
[`src/Tests/BusinessLayer/SerialReportingTest.cpp`](https://github.com/UCSolarCarTeam/Epsilon-Telemetry-Test-Tool/blob/master/src/Tests/BusinessLayer/SerialReportingTest.cpp)
Lines 637 and 638

Right and left swapped
[`src/Tests/BusinessLayer/SerialReportingTest.cpp`](https://github.com/UCSolarCarTeam/Epsilon-Telemetry-Test-Tool/blob/master/src/Tests/BusinessLayer/SerialReportingTest.cpp)
Line 331 and 332

Left and Right do not match communications protocol *
[`src/BusinessLayer/SerialReporting.cpp`](https://github.com/UCSolarCarTeam/Epsilon-Telemetry-Test-Tool/blob/master/src/BusinessLayer/SerialReporting.cpp)
Lines 140 and 141

Missing Alive
[`src/Tests/BusinessLayer/SerialReportingTest.cpp`](https://github.com/UCSolarCarTeam/Epsilon-Telemetry-Test-Tool/blob/master/src/Tests/BusinessLayer/SerialReportingTest.cpp)
Line 633
Therefore Line 641 should be Util::writeBoolsIntoArray(data, 2, lightsStatus, 6);

Offset for battery faults is off
[`src/Tests/BusinessLayer/SerialReportingTest.cpp`](https://github.com/UCSolarCarTeam/Epsilon-Telemetry-Test-Tool/blob/master/src/Tests/BusinessLayer/SerialReportingTest.cpp)
Line 490: Should be Util::writeBoolsIntoArray(data, 4, limitFlagsArray, 16);

FOR BACK EMF IMAGINARY
Make sure you change the payload packet offsets if they are there

Back EMF Imaginary shouldn't exist
[`src/BusinessLayer/SerialReporting.cpp`](https://github.com/UCSolarCarTeam/Epsilon-Telemetry-Test-Tool/blob/master/src/BusinessLayer/SerialReporting.cpp)
Line 114

Back EMF Imaginary shouldn't exist
[`src/DataLayer/MotorDetailsData.h`](https://github.com/UCSolarCarTeam/Epsilon-Telemetry-Test-Tool/blob/master/src/DataLayer/MotorDetailsData.h)
Line 13 and 30

Back EMF Imaginary shouldn't exist
[`src/Tests/BusinessLayer/SerialReportingTest.cpp`](https://github.com/UCSolarCarTeam/Epsilon-Telemetry-Test-Tool/blob/master/src/Tests/BusinessLayer/SerialReportingTest.cpp)
Line 259 and 290

Spelling Error
[`src/BusinessLayer/SerialReporting.cpp`](https://github.com/UCSolarCarTeam/Epsilon-Telemetry-Test-Tool/blob/master/src/BusinessLayer/SerialReporting.cpp)
Line 177 and 187: Should be motor, not mootor

Spelling Error
[`src/DataLayer/MotorFaultsData.h`](https://github.com/UCSolarCarTeam/Epsilon-Telemetry-Test-Tool/blob/master/src/DataLayer/MotorFaultsData.h)
Lines 9, 26, 45 and 63, should be motor, not mootor

Spelling Error
[`src/Tests/BusinessLayer/SerialReportingTest.cpp`](https://github.com/UCSolarCarTeam/Epsilon-Telemetry-Test-Tool/blob/master/src/Tests/BusinessLayer/SerialReportingTest.cpp)
Lines 384, 394: Should be motor, not mootor

~~Wrong packet ID *
[`src/Tests/BusinessLayer/SerialReportingTest.cpp`](https://github.com/UCSolarCarTeam/Epsilon-Telemetry-Test-Tool/blob/master/src/Tests/BusinessLayer/SerialReportingTest.cpp)
Line 644: should be 0x10~~
Resolved

**Comment by bill-luu** [comment]
> Left and Right do not match communications protocol *
src/BusinessLayer/SerialReporting.cpp
Lines 140 and 141

> Right and left swapped
src/Tests/BusinessLayer/SerialReportingTest.cpp
Line 331 and 332

> Aux in music
src/Tests/BusinessLayer/SerialReportingTest.cpp
Line 337
Util::writeBoolsIntoArray also need to be changed, corresponding to changes made with music

> Offset for battery faults is off
src/Tests/BusinessLayer/SerialReportingTest.cpp
Line 490: Should be Util::writeBoolsIntoArray(data, 4, limitFlagsArray, 16);

> Right and Left Switched
src/Tests/BusinessLayer/SerialReportingTest.cpp
Lines 637 and 638

> Missing Alive
src/Tests/BusinessLayer/SerialReportingTest.cpp
Line 633
Therefore Line 641 should be Util::writeBoolsIntoArray(data, 2, lightsStatus, 6);

Quick look, the above represent actual errors in the code, and should be prioritized. 
The other changes are stylistic that would be nice to fix.
